model_name_or_path: D:/models/Qwen2.5-VL-3B-Instruct
trust_remote_code: true

stage: sft
do_train: true
finetuning_type: lora
lora_target: all

dataset: dataset
template: qwen2_vl
cutoff_len: 4096
max_samples: 30000
overwrite_cache: true
preprocessing_num_workers: 16

output_dir: saves/SFT_3B_1
logging_steps: 500
save_steps: 1000
plot_loss: true
overwrite_output_dir: true

per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 0.0005
num_train_epochs: 1
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000